// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPlanungsAPP.Data;

#nullable disable

namespace PersonalPlanungsAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalPlanungsAPP.Models.Kapazitaetsabweichung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Enddatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("MitarbeiterId")
                        .HasColumnType("int");

                    b.Property<double>("NeueKapazitaet")
                        .HasColumnType("float");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kapazitaetsabweichungen");
                });

            modelBuilder.Entity("PersonalPlanungsAPP.Models.KostenstelleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<int>("Bereichsnummer")
                        .HasColumnType("int");

                    b.Property<string>("Kostenstelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KostenstelleInfos");
                });

            modelBuilder.Entity("PersonalPlanungsAPP.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Arbeitsverhaeltnis")
                        .HasColumnType("int");

                    b.Property<int>("Austritt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Befristung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BefristungMax")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<int>("Bereichsnummer")
                        .HasColumnType("int");

                    b.Property<DateTime>("Eintrittsdatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Freistellung")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fte")
                        .HasColumnType("float");

                    b.Property<string>("Funktion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kostenstelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Kuendigung")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mengenabhaengigkeit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Verlaengerung1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Verlaengerung2")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mitarbeiter");
                });
#pragma warning restore 612, 618
        }
    }
}
